/**
 * Cinema multisala “CineMille”  - OpenAPI 3.0
 * This is a sample Cinema Server based on the OpenAPI 3.0 specification.  Users can search for shows scheduled for the next 3 weeks.   Cinema employees can look up archived shows, i.e., shows scheduled up to the day before the consultation
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Room } from './room';
import { ShowDate } from './showDate';
import { ShowTime } from './showTime';

export interface Show { 
    id: number;
    title?: string;
    time?: ShowTime;
    from?: ShowDate;
    to?: ShowDate;
    /**
     * Duration of the show in minutes.
     */
    duration?: number;
    idRoom?: number;
    room?: Room;
}